import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API = import.meta.env.VITE_API_BASE_URL || '/api';
const TOKEN = 'sahan_teach_token';
const USER = 'sahan_teach_user';

async function api(path, options = {}) {
  const token = localStorage.getItem(TOKEN);
  const res = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) } });
  const body = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(body.message || 'Request failed');
  return body;
}

function App() {
  const [user, setUser] = useState(() => JSON.parse(localStorage.getItem(USER) || 'null'));
  const [path, setPath] = useState(window.location.pathname);
  const [error, setError] = useState('');
  useEffect(() => { const onPop = () => setPath(window.location.pathname); window.addEventListener('popstate', onPop); return () => window.removeEventListener('popstate', onPop); }, []);
  const go = (next) => { window.history.pushState({}, '', next); setPath(next); setError(''); };
  const logout = () => { localStorage.removeItem(TOKEN); localStorage.removeItem(USER); setUser(null); go('/login'); };
  if (!user) return <Login onLogin={(u) => { setUser(u); go(u.role === 'admin' ? '/admin/promotion-queue' : '/dashboard'); }} />;
  const admin = user.role === 'admin';
  return <Shell user={user} go={go} logout={logout} admin={admin}>{admin ? <AdminRouter path={path} go={go} setError={setError} /> : <InstructorRouter path={path} go={go} setError={setError} />}{error && <div className="toast error">{error}</div>}</Shell>;
}

function Login({ onLogin }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const signIn = async (e) => { e.preventDefault(); setBusy(true); setError(''); try { const b = await api('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); localStorage.setItem(TOKEN, b.token); localStorage.setItem(USER, JSON.stringify(b.user)); onLogin(b.user); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  const magic = async () => { if (!email) return setError('Enter your approved email first.'); setBusy(true); setError(''); try { const b = await api('/auth/magic-link', { method: 'POST', body: JSON.stringify({ email }) }); setMessage(b.message); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <div className="auth"><div className="auth-card"><div className="logo"><span>S</span><div><b>Sahan</b><small>Teach</small></div></div><div className="eyebrow">INSTRUCTOR & PARTNER PORTAL</div><h1>Teach what you know.</h1><p className="muted">Manage courses, track earnings and request promotion on the main Sahan learner app.</p>{error && <div className="alert">{error}</div>}{message && <div className="success">{message}</div>}<form onSubmit={signIn}><label>Email<input type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com" required /></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Your password" required /></label><button className="primary wide" disabled={busy}>{busy ? 'Signing in…' : 'Sign in'}</button></form><div className="or"><span />or<span /></div><button className="secondary wide" onClick={magic} disabled={busy}>{busy ? 'Sending…' : 'Email me a magic link'}</button><p className="login-note">Instructor access is approval-only. There is no public signup.</p></div></div>;
}

function Shell({ user, go, logout, admin, children }) { const items = admin ? [['/admin/promotion-queue','Promotion queue','↗'],['/admin/courses','Course ranking','◎'],['/admin/instructors','Instructors','♙']] : [['/dashboard','Dashboard','⌂'],['/courses','Courses','▤'],['/payouts','Payouts','$']]; return <div className="portal"><aside><div className="brand"><span>S</span><div><b>Sahan</b><small>Teach</small></div></div><div className="portal-label">{admin ? 'ADMIN CONTROL' : 'INSTRUCTOR PORTAL'}</div><nav>{items.map(([p,label,icon]) => <button key={p} className={window.location.pathname === p ? 'active' : ''} onClick={() => go(p)}><span>{icon}</span>{label}</button>)}</nav><div className="side-bottom"><div className="mini-user"><span>{(user.name || 'A').slice(0,1)}</span><div><b>{user.name}</b><small>{user.email}</small></div></div><button className="ghost-link" onClick={logout}>Sign out</button></div></aside><main><header><div><span className="crumb">{admin ? 'ADMIN' : 'TEACH'}</span><strong>{admin ? 'Sahan control center' : 'Instructor workspace'}</strong></div><a href="https://sahan.com" target="_blank" rel="noreferrer">Open learner app ↗</a></header>{children}</main></div>; }

function InstructorRouter({ path, go, setError }) { if (path === '/dashboard') return <Dashboard go={go} />; if (path === '/courses') return <Courses go={go} setError={setError} />; if (path.startsWith('/courses/')) return <Promote id={path.split('/')[2]} go={go} setError={setError} />; if (path === '/payouts') return <Payouts setError={setError} />; return <Dashboard go={go} />; }
function AdminRouter({ path, setError }) { if (path === '/admin/courses') return <AdminCourses setError={setError} />; if (path === '/admin/instructors') return <AdminInstructors setError={setError} />; return <AdminQueue setError={setError} />; }
function Page({ title, sub, children }) { return <div className="page"><div className="page-head"><div><span className="eyebrow">SAHAN TEACH</span><h1>{title}</h1><p>{sub}</p></div></div>{children}</div>; }
function Metric({ label, value }) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div>; }
function Badge({ children, tone = 'blue' }) { return <span className={`badge ${tone}`}>{children}</span>; }
function PanelTitle({ title, action }) { return <div className="panel-title"><h2>{title}</h2>{action}</div>; }
function Empty({ text }) { return <div className="empty">{text}</div>; }

function Dashboard({ go }) { const [data, setData] = useState({ courses: [], enrollments_count: 0, revenue: 0, pending_payout: 0 }); useEffect(() => { api('/instructor/overview').then(setData).catch(() => {}); }, []); const approved = data.courses.filter(c => c.admin_approved).length; return <Page title="Good to see you." sub="Your Sahan teaching business at a glance."><div className="metric-grid"><Metric label="Learner enrollments" value={data.enrollments_count} /><Metric label="Course revenue" value={`$${Number(data.revenue).toFixed(2)}`} /><Metric label="Approved courses" value={`${approved}/${data.courses.length}`} /><Metric label="Pending payout" value={`$${Number(data.pending_payout).toFixed(2)}`} /></div><div className="grid-2"><section className="panel"><PanelTitle title="Your courses" action={<button className="link" onClick={() => go('/courses')}>Manage →</button>} />{data.courses.slice(0,4).map(c => <div className="course-row" key={c.id}><div className="cover">{c.title.slice(0,1)}</div><div><b>{c.title}</b><small>{c.status} · quality {Number(c.base_quality_score || 0).toFixed(1)}</small></div><Badge tone={c.admin_approved ? 'green' : 'amber'}>{c.admin_approved ? 'Approved' : 'Review'}</Badge><button className="link" onClick={() => go(`/courses/${c.id}/promote`)}>Promote →</button></div>)}{!data.courses.length && <Empty text="No courses assigned yet." />}</section><section className="panel dark"><span className="eyebrow">GROW YOUR REACH</span><h2>Get discovered by more learners.</h2><p>Request a paid visibility boost. Promotion adds a modest ranking weight only while the campaign is active.</p><button className="primary" onClick={() => go('/courses')}>Choose a course →</button></section></div></Page>; }

function Courses({ go, setError }) { const [courses, setCourses] = useState([]); useEffect(() => { api('/instructor/courses').then(b => setCourses(b.courses)).catch(e => setError(e.message)); }, [setError]); return <Page title="Your courses" sub="Manage your courses and request promotion for approved courses."><section className="panel table"><div className="table-head"><span>Course</span><span>Status</span><span>Rank</span><span>Promotion</span><span /></div>{courses.map(c => <div className="table-row" key={c.id}><div><b>{c.title}</b><small>{c.category || 'General'} · ${Number(c.price || 0).toFixed(0)}</small></div><Badge tone={c.admin_approved ? 'green' : 'amber'}>{c.admin_approved ? 'Approved' : 'Pending approval'}</Badge><span>{Number(c.rank_score || 0).toFixed(1)}</span>{c.active_promotion ? <Badge tone="blue">{c.active_promotion.tier}</Badge> : <span className="muted">None</span>}<button className="small-btn" disabled={!c.admin_approved} onClick={() => go(`/courses/${c.id}/promote`)}>Promote</button></div>)}{!courses.length && <Empty text="No courses assigned yet." />}</section></Page>; }

function Promote({ id, go, setError }) { const [course, setCourse] = useState(null); const [requests, setRequests] = useState([]); const [duration, setDuration] = useState(7); const [budget, setBudget] = useState(''); const [busy, setBusy] = useState(false); const load = () => Promise.all([api('/instructor/courses'), api('/instructor/promotion-requests')]).then(([c,r]) => { setCourse(c.courses.find(x => x.id === id)); setRequests(r.requests.filter(x => x.course_id === id)); }).catch(e => setError(e.message)); useEffect(() => { load(); }, [id]); const submit = async e => { e.preventDefault(); setBusy(true); try { await api('/instructor/promotion-requests', { method:'POST', body:JSON.stringify({ course_id:id, requested_duration_days:Number(duration), requested_budget:budget ? Number(budget) : null }) }); await load(); } catch(e) { setError(e.message); } finally { setBusy(false); } }; if (!course) return <Page title="Promotion" sub="Loading…" />; return <Page title={`Promote “${course.title}”`} sub="Paid promotion increases visibility without replacing quality signals."><div className="grid-2"><section className="panel"><span className="eyebrow">CURRENT RANK</span><div className="rank-big">{Number(course.rank_score || 0).toFixed(1)}</div><p className="muted">Quality score {Number(course.base_quality_score || 0).toFixed(1)} · {course.active_promotion ? `Active ${course.active_promotion.tier} boost` : 'No active boost'}</p><div className="notice">Promotion weight is capped at 25 and expires automatically at its end date.</div></section><section className="panel"><PanelTitle title="Request a promotion" /><form onSubmit={submit} className="form-grid"><label>Duration<select value={duration} onChange={e=>setDuration(e.target.value)}><option value="3">3 days</option><option value="7">7 days</option><option value="14">14 days</option><option value="30">30 days</option></select></label><label>Budget (optional)<input type="number" min="0" value={budget} onChange={e=>setBudget(e.target.value)} placeholder="USD" /></label><button className="primary wide" disabled={busy}>{busy ? 'Submitting…' : 'Request promotion'}</button></form></section></div><section className="panel"><PanelTitle title="Request history" />{requests.length ? requests.map(r => <div className="request" key={r.id}><div><b>{r.requested_duration_days} days</b><small>{new Date(r.created_at).toLocaleString()} · Budget {r.requested_budget ?? 'not specified'}</small></div><Badge tone={r.status==='approved'?'green':r.status==='rejected'?'red':'amber'}>{r.status}</Badge></div>) : <Empty text="No promotion requests yet." />}</section></Page>; }

function Payouts({ setError }) { const [data,setData]=useState({payouts:[],pending_balance:0}); useEffect(()=>{api('/instructor/payouts').then(setData).catch(e=>setError(e.message));},[setError]); return <Page title="Payouts" sub="Your approved earnings and payment history."><div className="metric-grid"><Metric label="Pending balance" value={`$${Number(data.pending_balance).toFixed(2)}`} /><Metric label="Paid out" value={`$${data.payouts.filter(x=>x.status==='paid').reduce((s,x)=>s+Number(x.amount),0).toFixed(2)}`} /></div><section className="panel table"><div className="table-head"><span>Period</span><span>Amount</span><span>Status</span><span>Paid</span></div>{data.payouts.map(p=><div className="table-row" key={p.id}><div><b>{p.period_start} → {p.period_end}</b></div><strong>${Number(p.amount).toFixed(2)}</strong><Badge tone={p.status==='paid'?'green':'amber'}>{p.status}</Badge><span>{p.paid_at ? new Date(p.paid_at).toLocaleDateString() : '—'}</span></div>)}{!data.payouts.length&&<Empty text="No payout records yet."/>}</section></Page>; }

function AdminQueue({ setError }) { const [items,setItems]=useState([]); const load=()=>api('/admin/promotion-requests?status=pending').then(b=>setItems(b.requests)).catch(e=>setError(e.message)); useEffect(()=>{load();},[]); const act=async(item,approve)=>{try{if(approve){const start=new Date();const end=new Date(start.getTime()+item.requested_duration_days*86400000);await api(`/admin/promotion-requests/${item.id}/approve`,{method:'POST',body:JSON.stringify({tier:'boosted',weight:10,amount_paid:Number(item.requested_budget||0),start_date:start.toISOString(),end_date:end.toISOString()})});}else await api(`/admin/promotion-requests/${item.id}/reject`,{method:'POST',body:JSON.stringify({admin_notes:'Not approved at this time.'})});load();}catch(e){setError(e.message)}}; return <Page title="Promotion queue" sub="Review visibility requests from approved instructors."><section className="panel table"><div className="table-head"><span>Instructor</span><span>Course</span><span>Request</span><span>Budget</span><span>Actions</span></div>{items.map(i=><div className="table-row" key={i.id}><div><b>{i.instructors?.name}</b><small>{i.instructors?.email}</small></div><div><b>{i.sahan_courses?.title}</b></div><span>{i.requested_duration_days} days</span><span>${Number(i.requested_budget||0).toFixed(2)}</span><div><button className="approve" onClick={()=>act(i,true)}>Approve</button><button className="reject" onClick={()=>act(i,false)}>Reject</button></div></div>)}{!items.length&&<Empty text="No pending promotion requests."/>}</section></Page>; }

function AdminCourses({ setError }) { const [courses,setCourses]=useState([]); const load=()=>api('/admin/courses').then(b=>setCourses(b.courses)).catch(e=>setError(e.message)); useEffect(()=>{load();},[]); const save=async(c,value)=>{try{await api('/admin/rank-overrides',{method:'POST',body:JSON.stringify({course_id:c.id,manual_score:Number(value)})});load();}catch(e){setError(e.message)}}; return <Page title="Course ranking" sub="Manual founder control is independent of paid promotion."><section className="panel table"><div className="table-head"><span>Course</span><span>Instructor</span><span>Quality</span><span>Manual score</span><span>Approved</span></div>{courses.map(c=>{const score=c.rank_overrides?.[0]?.manual_score??0;return <div className="table-row" key={c.id}><div><b>{c.title}</b><small>{c.status}</small></div><span>{c.instructors?.name||'—'}</span><span>{Number(c.base_quality_score||0).toFixed(1)}</span><input className="score" type="number" min="-50" max="50" defaultValue={score} onBlur={e=>save(c,e.target.value)}/><Badge tone={c.admin_approved?'green':'amber'}>{c.admin_approved?'Yes':'No'}</Badge></div>})}</section></Page>; }

function AdminInstructors({ setError }) { const [items,setItems]=useState([]); const [form,setForm]=useState({name:'',email:'',commission_rate:.7}); const load=()=>api('/admin/instructors').then(b=>setItems(b.instructors||[])).catch(e=>setError(e.message)); useEffect(()=>{load();},[]); const create=async e=>{e.preventDefault();try{const b=await api('/admin/instructors',{method:'POST',body:JSON.stringify(form)});window.alert(`Instructor created. Temporary password: ${b.temporary_password}`);setForm({name:'',email:'',commission_rate:.7});load();}catch(e){setError(e.message)}}; return <Page title="Instructors" sub="There is no public instructor signup. Only admins can create accounts."><div className="grid-2"><section className="panel"><PanelTitle title="Create instructor"/><form onSubmit={create} className="form-grid"><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Commission<input type="number" min="0" max="1" step=".01" value={form.commission_rate} onChange={e=>setForm({...form,commission_rate:e.target.value})}/></label><button className="primary wide">Create account</button></form></section><section className="panel"><span className="eyebrow">RULE</span><h2>Approval only.</h2><p className="muted">Accounts are created after offline approval. The instructor portal contains no signup flow.</p></section></div><section className="panel table"><div className="table-head"><span>Instructor</span><span>Commission</span><span>Status</span></div>{items.map(i=><div className="table-row" key={i.id}><div><b>{i.name}</b><small>{i.email}</small></div><span>{Math.round(Number(i.commission_rate)*100)}%</span><Badge tone={i.status==='active'?'green':'red'}>{i.status}</Badge></div>)}{!items.length&&<Empty text="No instructors yet."/>}</section></Page>; }

createRoot(document.getElementById('root')).render(<App />);
