import React, { useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase.js'
import './learner.css'

const nav = [['home','Home'],['discover','Discover'],['learning','My learning'],['settings','Settings']]
export default function LearnerDashboardPayments({ session, onSignOut, onNavigateTeach }) {
 const user=session?.user; const [page,setPage]=useState('home'),[profile,setProfile]=useState(null),[courses,setCourses]=useState([]),[enrollments,setEnrollments]=useState([]),[query,setQuery]=useState(''),[selected,setSelected]=useState(null),[courseData,setCourseData]=useState(null),[progress,setProgress]=useState([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[phone,setPhone]=useState('')
 const displayName=profile?.display_name||user?.user_metadata?.full_name||user?.email?.split('@')[0]||'Learner'; const initials=displayName.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()
 const load=async()=>{if(!user)return;const [p,c,e]=await Promise.all([supabase.from('sahan_profiles').select('id,display_name,username,avatar_url,bio,role').eq('id',user.id).maybeSingle(),supabase.rpc('get_sahan_marketplace_courses'),supabase.from('sahan_enrollments').select('id,course_id,status,progress,enrolled_at,completed_at').eq('user_id',user.id).order('enrolled_at',{ascending:false})]);if(p.error)setError(p.error.message);else setProfile(p.data);if(c.error)setError(c.error.message);else setCourses(c.data||[]);if(e.error)setError(e.error.message);else setEnrollments(e.data||[])}
 useEffect(()=>{load()},[user?.id])
 const verifyPayment=async(orderId)=>{setBusy(true);setMessage('Confirming payment…');setError('');const {data,error:e}=await supabase.functions.invoke('sahan-verify-payment',{body:{orderId}});if(e||data?.ok===false)setError(e?.message||data?.error||'Could not confirm payment.');else if(data.status==='paid'){setMessage('Payment confirmed. Your course is now enrolled.');await load()}else setMessage('Payment is still processing. Enrollment will only happen after provider confirmation.');setBusy(false)}
 useEffect(()=>{const p=new URLSearchParams(window.location.search),order=p.get('order');if(window.location.pathname==='/payment/success'&&order)verifyPayment(order);if(window.location.pathname==='/payment/failed')setError('Payment was not completed. Your enrollment was not created.')},[])
 const enrolledIds=useMemo(()=>new Set(enrollments.map(e=>e.course_id)),[enrollments]); const learning=useMemo(()=>courses.filter(c=>enrolledIds.has(c.id)),[courses,enrolledIds]); const filtered=useMemo(()=>courses.filter(c=>`${c.title} ${c.category} ${c.level}`.toLowerCase().includes(query.toLowerCase())),[courses,query])
 const openCourse=async(c)=>{setSelected(c);setCourseData(null);const {data:s,error:se}=await supabase.from('sahan_sections').select('id,title,sort_order').eq('course_id',c.id).order('sort_order');if(se){setError(se.message);return}const ids=(s||[]).map(x=>x.id);let lessons=[];if(ids.length){const {data:l,error:le}=await supabase.from('sahan_lessons').select('id,section_id,title,lesson_type,duration_minutes,sort_order,is_preview').in('section_id',ids).order('sort_order');if(le){setError(le.message);return}lessons=l||[]}const {data:p,error:pe}=await supabase.from('sahan_lesson_progress').select('lesson_id,completed').eq('user_id',user.id);if(pe){setError(pe.message);return}setProgress(p||[]);setCourseData({sections:s||[],lessons})}
 const freeEnroll=async(c)=>{setBusy(true);const {error:e}=await supabase.from('sahan_enrollments').insert({user_id:user.id,course_id:c.id,status:'active',progress:0});if(e&&!/duplicate key/i.test(e.message))setError(e.message);else{setMessage(`You are enrolled in ${c.title}.`);await load();await openCourse(c);setPage('learning')}setBusy(false)}
 const checkout=async(c)=>{if(c.is_free)return freeEnroll(c);if(!phone.trim()){setError('Enter your Somali mobile number, e.g. 25261XXXXXXXX.');return}setBusy(true);setError('');setMessage('Creating secure checkout…');const {data,error:e}=await supabase.functions.invoke('sahan-create-checkout',{body:{courseId:c.id,phone:phone.trim()}});if(e||data?.ok===false){setError(e?.message||data?.error||'Checkout could not be started.');setBusy(false);return}if(data.checkoutUrl)window.location.href=data.checkoutUrl;else{setError('Payment provider did not return a checkout page.');setBusy(false)}}
 const mark=async(lessonId,completed)=>{const {error:e}=await supabase.from('sahan_lesson_progress').upsert({user_id:user.id,lesson_id:lessonId,completed,updated_at:new Date().toISOString()},{onConflict:'user_id,lesson_id'});if(e){setError(e.message);return}const next=progress.filter(p=>p.lesson_id!==lessonId);next.push({lesson_id:lessonId,completed});setProgress(next);if(selected&&courseData){const total=courseData.lessons.length,done=courseData.lessons.filter(l=>next.some(p=>p.lesson_id===l.id&&p.completed)).length,pct=total?Math.round(done/total*100):0;await supabase.from('sahan_enrollments').update({progress:pct,status:pct===100?'completed':'active',completed_at:pct===100?new Date().toISOString():null}).eq('user_id',user.id).eq('course_id',selected.id);setEnrollments(x=>x.map(e=>e.course_id===selected.id?{...e,progress:pct,status:pct===100?'completed':'active'}:e))}}
 const saveProfile=async(name)=>{const {data,error:e}=await supabase.from('sahan_profiles').upsert({id:user.id,display_name:name.trim()},{onConflict:'id'}).select('id,display_name,username,avatar_url,bio,role').single();if(e)setError(e.message);else{setProfile(data);setMessage('Profile updated.')}}
 return <div className="learner-shell"><aside className="learner-sidebar"><button className="learner-brand" onClick={()=>setPage('home')}><span>S</span><b>Sahan</b></button><div className="learner-label">LEARNER</div>{nav.map(([id,label])=><button key={id} className={`learner-nav ${page===id?'active':''}`} onClick={()=>setPage(id)}>{label}</button>)}<div className="learner-spacer"/><button className="learner-teach" onClick={onNavigateTeach}>Teach on Sahan →</button><button className="learner-profile" onClick={()=>setPage('settings')}><span>{initials||'L'}</span><div><b>{displayName}</b><small>{user?.email}</small></div></button><button className="learner-signout" onClick={onSignOut}>Sign out</button></aside><main className="learner-main"><header className="learner-topbar"><div className="learner-search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search courses…"/></div><div className="learner-account"><span>{initials||'L'}</span>{displayName}</div></header>{message&&<div className="learner-message">{message}</div>}{error&&<div className="learner-error">{error}</div>}{page==='home'&&<Home name={displayName} learning={learning} discover={()=>setPage('discover')} learningPage={()=>setPage('learning')} open={openCourse}/>} {page==='discover'&&<Discover courses={filtered} enrolled={enrolledIds} busy={busy} open={openCourse} buy={checkout}/>} {page==='learning'&&<Learning courses={learning} discover={()=>setPage('discover')} open={openCourse}/>} {page==='settings'&&<Settings profile={profile} email={user?.email} save={saveProfile}/>}</main>{selected&&<Panel course={selected} data={courseData} enrolled={enrolledIds.has(selected.id)} progress={progress} busy={busy} phone={phone} setPhone={setPhone} close={()=>{setSelected(null);setCourseData(null)}} buy={()=>checkout(selected)} mark={mark}/>}</div>
}
function Home({name,learning,discover,learningPage,open}){return <div className="learner-content"><section className="learner-welcome"><div><div className="learner-kicker">YOUR LEARNING SPACE</div><h1>Welcome, {name}.</h1><p>Real courses, payments, enrollments and lesson progress from your Sahan account.</p><div className="learner-actions"><button onClick={discover}>Explore courses →</button><button className="secondary" onClick={learningPage}>My learning</button></div></div><div className="learner-identity"><span>{name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}</span><b>Verified learner account</b><small>Marketplace data is live from Supabase.</small></div></section><section><div className="learner-section-head"><h2>Continue learning</h2><p>Your enrolled courses.</p></div>{learning.length?<div className="learner-grid">{learning.slice(0,3).map(c=><Card key={c.id} c={c} enrolled open={()=>open(c)}/>)}</div>:<Empty text="You have no enrollments yet." action={discover}/>}</section></div>}
function Discover({courses,enrolled,busy,open,buy}){return <div className="learner-content"><div className="learner-page-title"><div className="learner-kicker">DISCOVER</div><h1>Find something worth learning.</h1><p>Only published and approved courses are shown. Prices, learners and ratings come from Supabase.</p></div>{courses.length?<div className="learner-grid">{courses.map(c=><Card key={c.id} c={c} enrolled={enrolled.has(c.id)} busy={busy} open={()=>open(c)} buy={()=>buy(c)}/>)}</div>:<Empty text="No published courses are available yet."/>}</div>}
function Learning({courses,discover,open}){return <div className="learner-content"><div className="learner-page-title"><div className="learner-kicker">MY LEARNING</div><h1>Your courses.</h1><p>Progress comes from lessons you actually complete.</p></div>{courses.length?<div className="learner-grid">{courses.map(c=><Card key={c.id} c={c} enrolled open={()=>open(c)}/>)}</div>:<Empty text="You have not enrolled in a course yet." action={discover}/>}</div>}
function Card({c,enrolled,busy,open,buy}){const price=c.is_free?'Free':`${c.currency||'USD'} ${Number(c.price||0).toFixed(2)}`;return <article className="learner-course"><button className="learner-course-main" onClick={open}><div className="learner-cover">{c.cover_url&&<img src={c.cover_url} alt=""/>}<span>{c.category||'Learning'}</span><b>{c.title?.[0]||'S'}</b></div><small>{c.level} · {c.lesson_count||0} lessons · {c.student_count||0} learners</small><h3>{c.title}</h3><p>{c.description||'Build useful skills with Sahan.'}</p><div className="learner-course-meta"><span>{c.rating?`★ ${c.rating}`:'No ratings yet'}{c.review_count?` · ${c.review_count} reviews`:''}</span><strong>{price}</strong></div></button>{enrolled?<div className="learner-enrolled">✓ Enrolled · {Math.round(Number(c.progress||0))}% complete</div>:<button className="learner-enroll" onClick={buy} disabled={busy}>{busy?'Opening checkout…':c.is_free?'Enroll free →':'Buy course →'}</button>}</article>}
function Panel({course,data,enrolled,progress,busy,phone,setPhone,close,buy,mark}){const done=new Set(progress.filter(p=>p.completed).map(p=>p.lesson_id)),total=data?.lessons?.length||course.lesson_count||0,count=data?.lessons?.filter(l=>done.has(l.id)).length||0,pct=total?Math.round(count/total*100):Number(course.progress||0);return <div className="learner-modal-backdrop" onClick={close}><section className="learner-modal" onClick={e=>e.stopPropagation()}><button className="learner-modal-close" onClick={close}>×</button><div className="learner-kicker">COURSE</div><h2>{course.title}</h2><p>{course.description||'Learn practical skills with Sahan.'}</p><div className="learner-course-stats"><span>{course.category||'Learning'}</span><span>{course.level}</span><span>{course.rating?`★ ${course.rating}`:'No ratings yet'}</span><span>{course.student_count||0} learners</span></div>{enrolled?<><div className="learner-progress"><div><b>{pct}% complete</b><span>{count} of {total} lessons</span></div><i><em style={{width:`${pct}%`}}/></i></div>{data?<div className="learner-sections">{data.sections.map(s=><div className="learner-section" key={s.id}><h3>{s.title}</h3>{data.lessons.filter(l=>l.section_id===s.id).map(l=><label className="learner-lesson" key={l.id}><input type="checkbox" checked={done.has(l.id)} onChange={e=>mark(l.id,e.target.checked)}/><span><b>{l.title}</b><small>{l.lesson_type} · {l.duration_minutes||0} min</small></span></label>)}</div>)}</div>:<div className="learner-loading">Loading lessons…</div>}</>:<div className="learner-enroll-panel"><strong>{course.is_free?'Free course':`${course.currency||'USD'} ${Number(course.price||0).toFixed(2)}`}</strong>{course.is_free?<p>Enroll now and start learning immediately.</p>:<><p>Secure checkout through WaafiPay. Enrollment is created only after payment is confirmed server-side.</p><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Somali mobile number: 25261…"/><button className="learner-enroll" onClick={buy} disabled={busy}>{busy?'Starting secure checkout…':'Continue to payment →'}</button><small>Supports EVC Plus, ZAAD, SAHAL and WAAFI through the gateway.</small></>}</div>}</section></div>}
function Settings({profile,email,save}){const [name,setName]=useState(profile?.display_name||'');useEffect(()=>setName(profile?.display_name||''),[profile?.display_name]);return <div className="learner-content"><div className="learner-page-title"><div className="learner-kicker">SETTINGS</div><h1>Your account.</h1><p>Update your learner profile.</p></div><section className="learner-settings"><label>Full name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Email<input value={email||''} disabled/></label><button onClick={()=>save(name)} disabled={!name.trim()}>Save profile</button></section></div>}
function Empty({text,action}){return <div className="learner-empty"><h3>{text}</h3>{action&&<button onClick={action}>Explore courses →</button>}</div>}
