import React,{useEffect,useMemo,useState}from'react'
import{supabase}from'../lib/supabase.js'
import'./learner.css'

const NAV=[['home','⌂','Home'],['discover','◉','Explore'],['learning','▣','My Land'],['settings','⚙','Settings'],['community','◎','Community'],['messages','✉','Messaging']]

export default function LearnerDashboardJS({session,onSignOut,onNavigateTeach}){
 const user=session?.user
 const [page,setPage]=useState('home'),[collapsed,setCollapsed]=useState(false),[query,setQuery]=useState(''),[profile,setProfile]=useState(null),[courses,setCourses]=useState([]),[enrollments,setEnrollments]=useState([]),[selected,setSelected]=useState(null),[curriculum,setCurriculum]=useState(null),[progress,setProgress]=useState([]),[phone,setPhone]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const meta=user?.user_metadata||{}
 const name=profile?.display_name||meta.full_name||user?.email?.split('@')[0]||'Learner'
 const first=name.split(/\s+/)[0]
 const initials=name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'L'
 const load=async()=>{if(!user)return;const[p,c,e]=await Promise.all([supabase.from('sahan_profiles').select('id,display_name,username,avatar_url,bio,role').eq('id',user.id).maybeSingle(),supabase.rpc('get_sahan_marketplace_courses'),supabase.from('sahan_enrollments').select('id,course_id,status,progress,enrolled_at,completed_at').eq('user_id',user.id).order('enrolled_at',{ascending:false})]);if(p.error)setError(p.error.message);else setProfile(p.data);if(c.error)setError(c.error.message);else setCourses(c.data||[]);if(e.error)setError(e.error.message);else setEnrollments(e.data||[])}
 useEffect(()=>{load()},[user?.id])
 const enrolled=useMemo(()=>new Set(enrollments.map(e=>e.course_id)),[enrollments])
 const learning=useMemo(()=>courses.filter(c=>enrolled.has(c.id)),[courses,enrolled])
 const filtered=useMemo(()=>courses.filter(c=>`${c.title} ${c.category||''} ${c.level||''}`.toLowerCase().includes(query.toLowerCase())),[courses,query])
 const go=p=>{setPage(p);window.scrollTo({top:0,behavior:'smooth'})}
 const openCourse=async c=>{setSelected(c);setCurriculum(null);setError('');const{s,error:se}=await supabase.from('sahan_sections').select('id,title,sort_order').eq('course_id',c.id).order('sort_order');if(se){setError(se.message);return}const ids=(s||[]).map(x=>x.id);let lessons=[];if(ids.length){const{data,error:le}=await supabase.from('sahan_lessons').select('id,section_id,title,lesson_type,duration_minutes,sort_order,is_preview').in('section_id',ids).order('sort_order');if(le){setError(le.message);return}lessons=data||[]}const{data:p,error:pe}=await supabase.from('sahan_lesson_progress').select('lesson_id,completed').eq('user_id',user.id);if(pe){setError(pe.message);return}setProgress(p||[]);setCurriculum({sections:s||[],lessons})}
 const enrollCourse=async c=>{setBusy(true);setError('');if(c.is_free){const{error:e}=await supabase.from('sahan_enrollments').insert({user_id:user.id,course_id:c.id,status:'active',progress:0});if(e&&!/duplicate key/i.test(e.message))setError(e.message);else{setMessage(`You are enrolled in ${c.title}.`);await load();await openCourse(c);go('learning')}}else{if(!phone.trim()){setError('Enter your Somali mobile number, e.g. 25261XXXXXXXX.');setBusy(false);return}const{data,error:e}=await supabase.functions.invoke('sahan-create-checkout',{body:{courseId:c.id,phone:phone.trim()}});if(e||data?.ok===false)setError(e?.message||data?.error||'Checkout could not be started.');else if(data?.checkoutUrl)window.location.href=data.checkoutUrl;else setError('Payment provider did not return a checkout page.')}setBusy(false)}
 const markLesson=async(id,checked)=>{const{error:e}=await supabase.from('sahan_lesson_progress').upsert({user_id:user.id,lesson_id:id,completed:checked,updated_at:new Date().toISOString()},{onConflict:'user_id,lesson_id'});if(e){setError(e.message);return}const next=[...progress.filter(p=>p.lesson_id!==id),{lesson_id:id,completed:checked}];setProgress(next);if(selected&&curriculum){const total=curriculum.lessons.length,done=curriculum.lessons.filter(l=>next.some(p=>p.lesson_id===l.id&&p.completed)).length,pct=total?Math.round(done/total*100):0;await supabase.from('sahan_enrollments').update({progress:pct,status:pct===100?'completed':'active',completed_at:pct===100?new Date().toISOString():null}).eq('user_id',user.id).eq('course_id',selected.id);setEnrollments(v=>v.map(e=>e.course_id===selected.id?{...e,progress:pct,status:pct===100?'completed':'active'}:e))}}
 const saveProfile=async()=>{setBusy(true);const{data,error:e}=await supabase.from('sahan_profiles').upsert({id:user.id,display_name:name},{onConflict:'id'}).select().single();if(e)setError(e.message);else{setProfile(data);setMessage('Profile updated.')}setBusy(false)}
 return <div className={`learner-shell ${collapsed?'is-collapsed':''}`}><aside className="learner-sidebar"><div className="learner-brand-row"><button className="learner-brand" onClick={()=>go('home')}><span>S</span>{!collapsed&&<b>Sahan</b>}</button><button className="collapse" onClick={()=>setCollapsed(v=>!v)} aria-label="Toggle sidebar">{collapsed?'›':'‹'}</button></div><div className="learner-label">LEARNER</div>{NAV.map(([id,icon,label])=><button key={id} className={`learner-nav ${page===id?'active':''}`} title={label} onClick={()=>go(id)}><i>{icon}</i><span>{label}</span></button>)}<div className="learner-spacer"/><button className="learner-teach" onClick={onNavigateTeach}><span>Teach on Sahan</span>→</button><div className="side-user"><button onClick={()=>go('settings')}><span className="avatar">{initials}</span>{!collapsed&&<span><b>{name}</b><small>Learner</small></span>}</button><button className="learner-signout" onClick={onSignOut}>↪ Sign Out</button></div></aside><main className="learner-main"><header className="learner-topbar"><div className="learner-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search courses…"/></div><button className="account-pill" onClick={()=>go('settings')}><span className="avatar">{initials}</span><b>{first}</b></button></header>{message&&<div className="learner-message">✓ {message}</div>}{error&&<div className="learner-error">{error}</div>}{page==='home'&&<Home first={first} learning={learning} courses={courses} open={openCourse} discover={()=>go('discover')} myLearning={()=>go('learning')}/>} {page==='discover'&&<Discover courses={filtered} enrolled={enrolled} busy={busy} open={openCourse} enroll={enrollCourse}/>} {page==='learning'&&<Learning courses={learning} discover={()=>go('discover')} open={openCourse}/>} {page==='settings'&&<Settings name={name} email={user?.email} save={saveProfile} busy={busy}/>} {(page==='community'||page==='messages')&&<Simple title={page==='community'?'Community':'Messaging'} text={page==='community'?'Join course discussions and learn with other Sahan learners.':'Private conversations with instructors and other learners.'}/>}</main>{selected&&<CoursePanel course={selected} data={curriculum} enrolled={enrolled.has(selected.id)} progress={progress} phone={phone} setPhone={setPhone} busy={busy} close={()=>{setSelected(null);setCurriculum(null)}} enroll={()=>enrollCourse(selected)} mark={markLesson}/>}</div>
}
function Home({first,learning,courses,open,discover,myLearning}){return <div className="learner-content"><section className="learner-welcome"><div><div className="learner-kicker">YOUR LEARNING ROUTE</div><h1>Welcome back, {first}.</h1><p>Real courses, payments, enrollments and lesson progress — all connected to your Sahan account.</p><div className="learner-actions"><button onClick={discover}>Explore courses →</button><button className="secondary" onClick={myLearning}>My Land</button></div></div><div className="learner-ad"><small>YOUR SAHAN ACCOUNT</small><h3>Keep moving forward.</h3><p>{learning.length?`${learning.length} course${learning.length===1?'':'s'} in your learning land.`:'Choose your first course and start your trail.'}</p><button onClick={learning.length?myLearning:discover}>{learning.length?'Continue learning →':'Explore courses →'}</button></div></section><Section title="Continue learning" sub="Pick up exactly where you left off." action="View all" click={myLearning}/><div className="learner-grid">{learning.slice(0,3).map(c=><Card key={c.id} c={c} enrolled open={()=>open(c)}/>)}</div>{!learning.length&&<Empty action={discover}/>}<Section title="Explore courses" sub="Published courses available on Sahan." action="Explore all" click={discover}/><div className="learner-grid">{courses.slice(0,3).map(c=><Card key={c.id} c={c} open={()=>open(c)}/>)}</div></div>}
function Discover({courses,enrolled,busy,open,enroll}){return <div className="learner-content"><PageTitle kicker="EXPLORE" title="Find something worth learning." sub="Published courses from instructors across the Sahan marketplace."/><div className="learner-grid">{courses.map(c=><Card key={c.id} c={c} enrolled={enrolled.has(c.id)} busy={busy} open={()=>open(c)} buy={()=>enroll(c)}/>)}</div>{!courses.length&&<Empty/>}</div>}
function Learning({courses,discover,open}){return <div className="learner-content"><PageTitle kicker="MY LAND" title="Your courses." sub="Progress is tracked lesson by lesson — not just watch time."/><div className="learner-grid">{courses.map(c=><Card key={c.id} c={c} enrolled open={()=>open(c)}/>)}</div>{!courses.length&&<Empty action={discover}/>}</div>}
function Settings({name,email,save,busy}){return <div className="learner-content"><PageTitle kicker="SETTINGS" title="Your account." sub="Update your learner profile. Authentication is managed by Sahan Auth."/><div className="profile-card"><div className="profile-hero"><div className="big-avatar">{name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}</div><div><h2>{name}</h2><p>{email}</p></div></div><button className="save-profile" onClick={save} disabled={busy}>{busy?'Saving…':'Save profile'}</button></div></div>}
function Card({c,enrolled,busy,open,buy}){const price=c.is_free?'Free':`${c.currency||'USD'} ${Number(c.price||0).toFixed(2)}`;return <article className="learner-course"><button className="learner-course-main" onClick={open}><div className="learner-cover">{c.cover_url&&<img src={c.cover_url} alt=""/>}<span>{c.category||'Learning'}</span><b>{c.title?.[0]||'S'}</b></div><small>{c.level||'All levels'} · {c.lesson_count||0} lessons · {Number(c.student_count||0).toLocaleString()} learners</small><h3>{c.title}</h3><p>{c.description||'Build useful skills with Sahan.'}</p><div className="learner-course-meta"><span>{c.rating?`★ ${c.rating}`:'New course'}</span><strong>{price}</strong></div></button>{enrolled?<div className="learner-enrolled">✓ Enrolled · {Math.round(Number(c.progress||0))}% complete</div>:buy&&<button className="learner-enroll" disabled={busy} onClick={e=>{e.stopPropagation();buy()}}>{busy?'Opening…':c.is_free?'Enroll free →':'View course →'}</button>}</article>}
function CoursePanel({course,data,enrolled,progress,phone,setPhone,busy,close,enroll,mark}){const done=new Set(progress.filter(p=>p.completed).map(p=>p.lesson_id));const total=data?.lessons?.length||course.lesson_count||0;const count=data?.lessons?.filter(l=>done.has(l.id)).length||0;const pct=total?Math.round(count/total*100):Number(course.progress||0);return <div className="learner-modal-backdrop" onClick={close}><section className="learner-modal" onClick={e=>e.stopPropagation()}><button className="learner-modal-close" onClick={close}>×</button><div className="learner-kicker">COURSE</div><h2>{course.title}</h2><p>{course.description||'Learn practical skills with Sahan.'}</p><div className="learner-course-stats"><span>{course.category||'Learning'}</span><span>{course.level||'All levels'}</span><span>{Number(course.student_count||0).toLocaleString()} learners</span></div>{enrolled?<><div className="learner-progress"><div><b>{pct}% complete</b><span>{count} of {total} lessons</span></div><i><em style={{width:`${pct}%`}}/></i></div>{data?<div className="learner-sections">{data.sections.map(s=><div className="learner-section" key={s.id}><h3>{s.title}</h3>{data.lessons.filter(l=>l.section_id===s.id).map(l=><label className="learner-lesson" key={l.id}><input type="checkbox" checked={done.has(l.id)} onChange={e=>mark(l.id,e.target.checked)}/><span><b>{l.title}</b><small>{l.lesson_type} · {l.duration_minutes||0} min</small></span></label>)}</div>)}</div>:<div className="learner-loading">Loading curriculum…</div>}</>:<div className="learner-enroll-panel"><strong>{course.is_free?'Free':`${course.currency||'USD'} ${Number(course.price||0).toFixed(2)}`}</strong><p>{course.is_free?'Enroll now and start learning immediately.':'Enter your Somali mobile number to continue to checkout.'}</p>{!course.is_free&&<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="25261XXXXXXXX"/>}<button className="learner-enroll" onClick={enroll} disabled={busy}>{busy?'Opening…':course.is_free?'Enroll free →':'Continue to payment →'}</button></div>}</section></div>}
function Section({title,sub,action,click}){return <div className="learner-section-head"><div><h2>{title}</h2><p>{sub}</p></div>{action&&<button className="text-link" onClick={click}>{action} →</button>}</div>}
function PageTitle({kicker,title,sub}){return <div className="learner-page-title"><div className="learner-kicker">{kicker}</div><h1>{title}</h1><p>{sub}</p></div>}
function Empty({action}){return <div className="learner-empty"><h3>No routes charted yet.</h3><p>Choose a published course to start your learning trail.</p>{action&&<button onClick={action}>Explore courses →</button>}</div>}
function Simple({title,text}){return <div className="learner-content"><PageTitle kicker="SAHAN" title={title} sub={text}/><div className="learner-empty"><h3>Coming alive soon.</h3><p>This area is ready for the connected community and messaging features.</p></div></div>}
