import React, { useEffect, useMemo, useState } from 'react'
import './styles/app.css'

const courses = [
  { id: 1, title: 'Excel & Power BI for Real Work', creator: 'Sahan Academy', category: 'Business', level: 'Beginner', price: 29, students: 1280, progress: 68, lessons: 32, rating: 4.9 },
  { id: 2, title: 'Modern English Speaking', creator: 'Ayaan Teacher', category: 'Languages', level: 'All levels', price: 19, students: 842, progress: 42, lessons: 24, rating: 4.8 },
  { id: 3, title: 'Build Your First Online Business', creator: 'Hassan Noor', category: 'Business', level: 'Intermediate', price: 49, students: 516, progress: 12, lessons: 41, rating: 4.9 },
  { id: 4, title: 'Graphic Design From Zero', creator: 'Sahan Creative', category: 'Design', level: 'Beginner', price: 0, students: 2304, progress: 0, lessons: 18, rating: 4.7 },
  { id: 5, title: 'The Executive Power BI Masterclass', creator: 'Mariam Hassan', category: 'Business', level: 'Advanced', price: 129, students: 9340, progress: 0, lessons: 56, rating: 5, premium: true },
  { id: 6, title: 'Photography: See the Light', creator: 'Omar Studio', category: 'Photography', level: 'All levels', price: 79, students: 7210, progress: 0, lessons: 38, rating: 4.9 },
  { id: 7, title: 'AI for Modern Work', creator: 'Nadia Ahmed', category: 'Technology', level: 'Intermediate', price: 59, students: 6800, progress: 0, lessons: 34, rating: 4.9 },
  { id: 8, title: 'English Fluency in 90 Days', creator: 'Ayaan Teacher', category: 'Languages', level: 'All levels', price: 39, students: 5900, progress: 0, lessons: 42, rating: 4.8 },
  { id: 9, title: 'Brand Design Masterclass', creator: 'Sahan Creative', category: 'Design', level: 'Advanced', price: 99, students: 4800, progress: 0, lessons: 29, rating: 4.9 },
  { id: 10, title: 'Start Investing With Confidence', creator: 'Yusuf Finance', category: 'Finance', level: 'Beginner', price: 69, students: 4200, progress: 0, lessons: 27, rating: 4.8 },
]
const nav = [['home', 'Home'], ['discover', 'Discover'], ['learning', 'My learning'], ['community', 'Community'], ['live', 'Live & events'], ['messages', 'Messages'], ['certificates', 'Certificates'], ['settings', 'Settings']]
const categories = ['All', 'Business', 'Design', 'Technology', 'Languages', 'Photography', 'Finance']
function Icon({ name, size = 18 }) { const p = { home:<><path d="m3 10 9-7 9 7"/><path d="M5 9v11h14V9"/><path d="M9 20v-6h6v6"/></>, search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>, book:<><path d="M4 4.5A2.5 2.5 0 0 1 6.5 2H20v18H6.5A2.5 2.5 0 0 1 4 17.5z"/><path d="M4 17.5A2.5 2.5 0 0 1 6.5 15H20"/></>, users:<><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></>, calendar:<><rect x="3" y="4" width="18" height="17" rx="2"/><path d="M16 2v4M8 2v4M3 10h18"/></>, message:<path d="M21 11.5a8.38 8.38 0 0 1-9 8.5 9.7 9.7 0 0 1-4-.8L3 21l1.8-4A8.1 8.1 0 0 1 3 11.5 8.38 8.38 0 0 1 12 3a8.38 8.38 0 0 1 9 8.5Z"/>, check:<path d="m5 12 4 4L19 6"/>, settings:<><circle cx="12" cy="12" r="3"/><path d="M19 12a7 7 0 0 0-.1-1l2-1.5-2-3.4-2.3 1a8 8 0 0 0-1.7-1L14.6 3h-4l-.3 2.1a8 8 0 0 0-1.7 1l-2.3-1-2 3.4 2 1.5a7 7 0 0 0 0 2l-2 1.5 2 3.4 2.3-1a8 8 0 0 0 1.7 1l.3 2.1h4l.3-2.1a8 8 0 0 0 1.7-1l2.3 1 2-3.4-2-1.5c.1-.3.1-.7.1-1Z"/></>, bell:<><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></>, arrow:<><path d="M5 12h14"/><path d="m13 6 6 6-6 6"/></>, close:<><path d="m6 6 12 12M18 6 6 18"/></> }; return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">{p[name]||p.home}</svg> }
function read(key, fallback) { try { return JSON.parse(localStorage.getItem(key)) ?? fallback } catch { return fallback } }
function write(key, value) { try { localStorage.setItem(key, JSON.stringify(value)) } catch {} }
export default function App() {
 const [page,setPage]=useState('home'),[query,setQuery]=useState(''),[toast,setToast]=useState(''),[selected,setSelected]=useState(null),[enrolled,setEnrolled]=useState(()=>read('sahan-enrolled',[1,2])),[saved,setSaved]=useState(()=>read('sahan-saved',[])),[settings,setSettings]=useState(()=>read('sahan-settings',{email:true,reminders:true}));
 useEffect(()=>write('sahan-enrolled',enrolled),[enrolled]); useEffect(()=>write('sahan-saved',saved),[saved]); useEffect(()=>write('sahan-settings',settings),[settings]);
 const notify=m=>{setToast(m);clearTimeout(window.__sahanToast);window.__sahanToast=setTimeout(()=>setToast(''),2500)}; const filtered=useMemo(()=>courses.filter(c=>`${c.title} ${c.creator} ${c.category}`.toLowerCase().includes(query.toLowerCase())),[query]); const go=p=>{setPage(p);window.scrollTo({top:0,behavior:'smooth'})}; const toggle=id=>setSaved(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]); const buy=c=>{if(!enrolled.includes(c.id))setEnrolled(v=>[...v,c.id]);notify(c.price?`Demo checkout started for ${c.title}. Connect your payment provider for live payments.`:`You're enrolled in ${c.title}.`);setSelected(null);go('learning')};
 return <div className="sahan-app"><aside className="sidebar"><button className="brand" onClick={()=>go('home')}><span className="brand-mark">S</span><span><strong>Sahan</strong><small>Learn beautifully.</small></span></button><div className="side-label">Library</div>{nav.map(([id,label])=><button key={id} className={`nav-item ${page===id?'active':''}`} onClick={()=>go(id)}><Icon name={id==='home'?'home':id==='discover'?'search':id==='learning'?'book':id==='community'?'users':id==='live'?'calendar':id==='messages'?'message':id==='certificates'?'check':'settings'}/>{label}</button>)}<div className="sidebar-spacer"/><div className="sidebar-note"><b>✦ Teach on Sahan</b><p>Instructor tools live in the private Teach portal.</p><button onClick={()=>notify('Instructor access is handled at teach.sahan.com.')}>Learn more <Icon name="arrow" size={12}/></button></div><div className="profile-mini"><span className="avatar">A</span><span><strong>Abdikadir</strong><small>Learner</small></span></div></aside><main className="main-content"><header className="topbar"><button className="mobile-brand" onClick={()=>go('home')}>Sahan</button><div className="global-search"><Icon name="search" size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search courses, teachers, communities..."/></div><div className="top-actions"><button className="icon-btn" onClick={()=>notify('No new notifications.') }><Icon name="bell" size={18}/></button><button className="avatar avatar-sm" onClick={()=>go('settings')}>A</button></div></header><div className="content-wrap">{page==='home'&&<Home go={go} onOpen={setSelected} enrolled={enrolled}/>} {page==='discover'&&<Discover courses={filtered} onOpen={setSelected} saved={saved} toggle={toggle}/>} {page==='learning'&&<Learning courses={courses.filter(c=>enrolled.includes(c.id))} go={go} onOpen={setSelected}/>} {page==='community'&&<Community notify={notify}/>} {page==='live'&&<Live notify={notify}/>} {page==='messages'&&<Messages notify={notify}/>} {page==='certificates'&&<Certificates notify={notify}/>} {page==='settings'&&<Settings settings={settings} setSettings={setSettings} notify={notify}/>}</div></main>{selected&&<CourseModal course={selected} enrolled={enrolled.includes(selected.id)} saved={saved.includes(selected.id)} onClose={()=>setSelected(null)} onBuy={buy} onSave={()=>toggle(selected.id)}/>} {toast&&<div className="toast">✓ {toast}</div>}</div>
}
function Home({go,onOpen,enrolled}){const premium=courses[4];return <><section className="welcome"><div><div className="eyebrow">SAHAN · YOUR LEARNING SPACE</div><h1>Learn something<br/><em>worth knowing.</em></h1><p>Courses, live classes and communities from people who know their craft.</p><div className="actions"><button className="primary" onClick={()=>go('discover')}>Explore courses <Icon name="arrow" size={14}/></button><button className="ghost" onClick={()=>go('live')}>See live classes</button></div></div><button className="hero-card" onClick={()=>onOpen(premium)}><span className="premium-label">SAHAN PREMIUM</span><div><small>MASTERCLASS · FEATURED</small><h2>{premium.title}</h2><p>Learn from an expert-led masterclass selected for learners who want to go further.</p><span>★★★★★ {premium.rating} · {premium.students.toLocaleString()} learners</span><b>View masterclass <Icon name="arrow" size={13}/></b></div></button></section><SectionHead title="Continue learning" sub="Pick up exactly where you left off." action="View all" click={()=>go('learning')}/><div className="course-grid">{courses.filter(c=>enrolled.includes(c.id)).slice(0,3).map(c=><CourseCard key={c.id} course={c} onClick={()=>onOpen(c)}/>)}</div><section className="premium-strip"><div><small>FEATURED</small><h2>Learn from the best.</h2><p>Premium masterclasses from respected teachers and industry leaders.</p></div><button className="dark-btn" onClick={()=>go('discover')}>Explore premium <Icon name="arrow" size={14}/></button></section><section><SectionHead title="Top 10 classes" sub="The courses learners are choosing most right now." action="See all" click={()=>go('discover')}/><div className="top-ten">{courses.map((c,i)=><button className="rank-row" key={c.id} onClick={()=>onOpen(c)}><strong>{String(i+1).padStart(2,'0')}</strong><span className={`rank-cover c${i%6+1}`}>{c.title[0]}</span><span><b>{c.title}</b><small>{c.creator} · {c.students.toLocaleString()} learners</small></span><span>★ {c.rating}</span><strong>{c.price?'$'+c.price:'Free'}</strong><Icon name="arrow" size={14}/></button>)}</div></section><SectionHead title="Explore by interest" sub="Find your next direction."/><div className="interest-grid">{['Business','Design','Technology','Languages'].map((x,i)=><button className={`interest i${i+1}`} key={x} onClick={()=>go('discover')}><b>{x}</b><small>Explore {x.toLowerCase()} courses</small><Icon name="arrow" size={14}/></button>)}</div></>}
function SectionHead({title,sub,action,click}){return <div className="section-head"><div><h2>{title}</h2><p>{sub}</p></div>{action&&<button className="text-btn" onClick={click}>{action} <Icon name="arrow" size={12}/></button>}</div>}
function PageTitle({kicker,title,sub}){return <div className="page-title"><div><div className="eyebrow">{kicker}</div><h1>{title}</h1><p>{sub}</p></div></div>}
function CourseCard({course,onClick}){return <button className="course-card" onClick={onClick}><div className={`course-cover c${course.id%6+1}`}>{course.premium&&<b>PREMIUM</b>}<span>{course.category}</span><strong>{course.title[0]}</strong></div><div className="course-body"><small>{course.level} · {course.lessons} lessons</small><h3>{course.title}</h3><p>{course.creator}</p><div><span>★ {course.rating} · {course.students.toLocaleString()}</span><b>{course.price?'$'+course.price:'Free'}</b></div></div></button>}
function Discover({courses,onOpen,saved,toggle}){const [cat,setCat]=useState('All');const list=cat==='All'?courses:courses.filter(c=>c.category===cat);return <><PageTitle kicker="DISCOVER" title="Find something worth learning." sub="Explore courses, teachers and ideas from every category."/><div className="filter-row">{categories.map(c=><button className={cat===c?'active':''} key={c} onClick={()=>setCat(c)}>{c}</button>)}</div><div className="course-grid four">{list.map(c=><div className="discover-item" key={c.id}><CourseCard course={c} onClick={()=>onOpen(c)}/><button className="save-btn" onClick={()=>toggle(c.id)}>{saved.includes(c.id)?'Saved':'Save'}</button></div>)}</div>{!list.length&&<Empty/>}</>}
function Learning({courses,go,onOpen}){return <><PageTitle kicker="MY LEARNING" title="Your learning space." sub="Courses you started, saved and completed."/>{courses.length?<><div className="stats-row"><Stat n={courses.length} label="Courses"/><Stat n={courses.reduce((a,c)=>a+Math.round(c.lessons*c.progress/100),0)} label="Lessons done"/><Stat n="6h 42m" label="Learning time"/><Stat n="1" label="Certificates"/></div><div className="course-grid">{courses.map(c=><CourseCard key={c.id} course={c} onClick={()=>onOpen(c)}/>)}</div></>:<Empty action={()=>go('discover')}/>}</>}
function Stat({n,label}){return <div className="stat"><b>{n}</b><span>{label}</span></div>}
function Empty({action}){return <div className="empty-state"><h2>Your library is waiting.</h2><p>Find a course you love and start learning.</p>{action&&<button className="primary" onClick={action}>Discover courses</button>}</div>}
function Community({notify}){return <><PageTitle kicker="COMMUNITY" title="Learn together." sub="Ask questions, share progress and meet people learning alongside you."/><div className="community-grid">{['Designers in Sahan','Power BI Learners','English Speaking Club'].map((x,i)=><article className="community-card" key={x}><div className={`community-art i${i+1}`}>{x[0]}</div><h3>{x}</h3><p>{[284,517,193][i]} members · active today</p><button className="primary" onClick={()=>notify(`Joined ${x}.`)}>Join community</button></article>)}</div><div className="feed-card"><b>Community feed</b>{['Just finished my first Power BI dashboard.','What is the best way to practice spoken English every day?','Sharing a brand concept I made this weekend.'].map((x,i)=><div className="feed-row" key={x}><span className="avatar">{String.fromCharCode(77+i)}</span><div><b>{['Muna','Hassan','Sagal'][i]}</b><p>{x}</p><small>{i+4} min ago · {i+2} replies</small></div></div>)}</div></>}
function Live({notify}){return <><PageTitle kicker="LIVE & EVENTS" title="Learn in the moment." sub="Live classes, workshops and conversations with people worth listening to."/><div className="live-feature"><span>● LIVE SOON</span><h2>Power BI Office Hours</h2><p>Bring your questions and build alongside Mariam Hassan.</p><button className="primary" onClick={()=>notify('Reminder set.')}>Set reminder</button></div><div className="event-list">{['AI for Modern Work','English Fluency Workshop','Brand Design Critique'].map((x,i)=><div className="event-row" key={x}><b>{20+i} AUG</b><div><strong>{x}</strong><small>{['Nadia Ahmed','Ayaan Teacher','Sahan Creative'][i]} · {i+1} hour</small></div><button className="ghost" onClick={()=>notify('Reminder set.')}>Remind me</button></div>)}</div></>}
function Messages({notify}){return <><PageTitle kicker="MESSAGES" title="Your conversations." sub="Stay connected with teachers and learning communities."/><div className="message-list">{[['Mariam Hassan','Your Power BI masterclass is ready for you.'],['Ayaan Teacher','See you in the English workshop!'],['Sahan Creative','I replied to your community post.']].map(([n,t])=><button className="message-row" key={n} onClick={()=>notify(`Opening conversation with ${n}.`)}><span className="avatar">{n[0]}</span><span><b>{n}</b><small>{t}</small></span><Icon name="arrow" size={14}/></button>)}</div></>}
function Certificates({notify}){const c={course:'Excel & Power BI for Real Work',issuer:'Sahan Academy',instructor:'Mariam Hassan',date:'August 12, 2026',no:'SAH-2026-001284'};return <><PageTitle kicker="YOUR ACHIEVEMENTS" title="Certificates" sub="Certificates issued to you by the creators of courses you have completed."/><div className="certificate-library"><div className="certificate-list"><b>ISSUED TO YOU · 1</b><div className="certificate-list-item"><span className="certificate-thumb">S</span><span><b>{c.course}</b><small>{c.issuer} · {c.date}</small></span><em>Verified</em></div></div><div className="certificate-detail"><div className="certificate-paper"><small>SAHAN</small><label>CERTIFICATE OF COMPLETION</label><h2>{c.course}</h2><p>This certificate is proudly presented to</p><h3>Abdikadir</h3><p>for successfully completing the requirements established by</p><b>{c.instructor}</b><footer><span>{c.date}</span><span>{c.no}</span><span>Issued by {c.issuer}</span></footer></div><button className="primary" onClick={()=>{notify('Opening print dialog.');window.print()}}>View / print certificate</button></div></div></>}
function Settings({settings,setSettings,notify}){return <><PageTitle kicker="SETTINGS" title="Make Sahan yours." sub="Control your learning preferences and notifications."/><div className="settings-card">{[['email','Email updates','Occasional product and learning recommendations.'],['reminders','Learning reminders','Get reminders when a course is waiting for you.']].map(([key,title,desc])=><div className="setting-row" key={key}><span><b>{title}</b><small>{desc}</small></span><button className={`toggle ${settings[key]?'on':''}`} onClick={()=>setSettings(s=>({...s,[key]:!s[key]}))}><i/></button></div>)}<div className="setting-row"><span><b>Account</b><small>Abdikadir · Learner</small></span><button className="ghost" onClick={()=>notify('Account management is ready.')}>Manage</button></div></div></>}
function CourseModal({course,enrolled,saved,onClose,onBuy,onSave}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="course-modal"><button className="modal-close" onClick={onClose}><Icon name="close"/></button><div className={`modal-cover c${course.id%6+1}`}><span>{course.category}</span><b>{course.title[0]}</b></div><div className="modal-body"><div className="eyebrow">{course.premium?'SAHAN PREMIUM':'COURSE'} · {course.level}</div><h2>{course.title}</h2><p>By {course.creator}</p><div className="modal-meta"><span>★ {course.rating}</span><span>{course.students.toLocaleString()} learners</span><span>{course.lessons} lessons</span></div><p>Build practical skills with structured lessons and a learning community around the topic.</p><div className="modal-actions">{enrolled?<button className="primary" onClick={onClose}>Continue learning <Icon name="arrow" size={13}/></button>:<button className="primary" onClick={()=>onBuy(course)}>{course.price?`Buy for $${course.price}`:'Enroll free'} <Icon name="arrow" size={13}/></button>}<button className="ghost" onClick={onSave}>{saved?'Saved':'Save for later'}</button></div></div></div></div>}
